import React, { useEffect, useState } from 'react';
import { Pin, RefreshCw, Zap } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { Modal } from '../ui/Modal';
import { Button } from '../ui/Button';
import {
  AutomationTrigger,
  RecurrenceSchedule,
  Task,
  TaskPriority,
  TaskType,
} from '../../types';
import { AUTOMATION_TRIGGER_LABELS, RECURRENCE_LABELS } from '../../lib/taskUtils';
import { isEmployeeAssignable } from '../../lib/employeeUtils';

interface CreateTaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  editTask?: Task | null;
}

const inputCls =
  'w-full px-3.5 py-2 bg-[#FAF8F5] border border-[#DDD7CB] rounded-[10px] text-sm text-[#24221F] focus:outline-none focus:ring-2 focus:ring-[#386641]';
const labelCls =
  'block text-xs font-semibold text-[#45413B] uppercase tracking-wider mb-1 font-body';

// Domain work kind — drives which departments are eligible for assignment
// and is stored on the task. Task Type below is the lifecycle shape.
const WORK_TYPE_OPTIONS = [
  { value: 'cleaning', label: 'Cleaning' },
  { value: 'maintenance', label: 'Maintenance' },
  { value: 'inspection', label: 'Inspection' },
  { value: 'housekeeping', label: 'Housekeeping' },
  { value: 'other', label: 'Other' },
];

const TYPE_OPTIONS: { value: TaskType; label: string; hint: string; icon: React.ReactNode }[] = [
  {
    value: 'fixed',
    label: 'Fixed',
    hint: 'One-time task with a due date',
    icon: <Pin className="w-4 h-4" />,
  },
  {
    value: 'repetitive',
    label: 'Repetitive',
    hint: 'Recurs on a set schedule',
    icon: <RefreshCw className="w-4 h-4" />,
  },
  {
    value: 'automated',
    label: 'Automated',
    hint: 'Auto-generated by a trigger',
    icon: <Zap className="w-4 h-4" />,
  },
];

export const CreateTaskModal: React.FC<CreateTaskModalProps> = ({ isOpen, onClose, editTask }) => {
  const {
    createTask,
    updateTask,
    currentPropertyEmployees,
    currentPropertyZones,
    currentPropertyRooms,
    currentPropertyWashrooms,
    activeProperty,
  } = useApp();

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [workType, setWorkType] = useState('other');
  const [taskType, setTaskType] = useState<TaskType>('fixed');
  const [employeeUid, setEmployeeUid] = useState('');
  const [supervisorUid, setSupervisorUid] = useState('');
  const [roomUid, setRoomUid] = useState('');
  const [washroomUid, setWashroomUid] = useState('');
  const [zoneUid, setZoneUid] = useState('');
  const [priority, setPriority] = useState<TaskPriority>('medium');
  const [dueDate, setDueDate] = useState('');
  const [dueTime, setDueTime] = useState('');
  const [recurrence, setRecurrence] = useState<RecurrenceSchedule>('daily');
  const [startTime, setStartTime] = useState('');
  const [windowEnd, setWindowEnd] = useState('');
  const [runsFrom, setRunsFrom] = useState('');
  const [runsUntil, setRunsUntil] = useState('');
  const [runsForever, setRunsForever] = useState(true);
  const [intervalDays, setIntervalDays] = useState('3');
  const [trigger, setTrigger] = useState<AutomationTrigger>('bed_available_after_checkout');
  const [scopeZoneUid, setScopeZoneUid] = useState('');
  const [templateTitle, setTemplateTitle] = useState('');
  const [templateDescription, setTemplateDescription] = useState('');
  const [ruleAssigneeUid, setRuleAssigneeUid] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const isEdit = !!editTask;

  // Prefill in edit mode
  useEffect(() => {
    if (editTask) {
      setTitle(editTask.title);
      setDescription(editTask.description || '');
      setWorkType(editTask.work_type || 'other');
      setTaskType(editTask.task_type);
      setEmployeeUid(editTask.employee_uid || editTask.assigned_to_uid || '');
      setSupervisorUid(editTask.supervisor_uid || '');
      setRoomUid(editTask.room_uid || '');
      setWashroomUid(editTask.washroom_uid || '');
      setZoneUid(editTask.zone_uid || '');
      setPriority(editTask.priority);
      setDueDate(editTask.due_date || '');
      setDueTime(editTask.due_time || '');
      setRecurrence(editTask.recurrence || 'daily');
      setStartTime(editTask.start_time || '');
      setWindowEnd(editTask.recurrence_window_end || '');
      setRunsFrom(editTask.recurrence_start_date || '');
      setRunsUntil(editTask.recurrence_end_date || '');
      setRunsForever(!editTask.recurrence_end_date);
      setIntervalDays(String(editTask.recurrence_interval_days || 3));
      setTrigger(editTask.automation_rule?.trigger || 'bed_available_after_checkout');
      setScopeZoneUid(editTask.automation_rule?.scope_zone_uid || '');
      setTemplateTitle(editTask.automation_rule?.template_title || '');
      setTemplateDescription(editTask.automation_rule?.template_description || '');
      setRuleAssigneeUid(editTask.automation_rule?.assign_to_uid || '');
    }
  }, [editTask]);

  const reset = () => {
    setTitle('');
    setDescription('');
    setWorkType('other');
    setTaskType('fixed');
    setEmployeeUid('');
    setSupervisorUid('');
    setRoomUid('');
    setWashroomUid('');
    setZoneUid('');
    setPriority('medium');
    setDueDate('');
    setDueTime('');
    setRecurrence('daily');
    setStartTime('');
    setWindowEnd('');
    setRunsFrom('');
    setRunsUntil('');
    setRunsForever(true);
    setIntervalDays('3');
    setTrigger('bed_available_after_checkout');
    setScopeZoneUid('');
    setTemplateTitle('');
    setTemplateDescription('');
    setRuleAssigneeUid('');
  };

  const handleClose = () => {
    reset();
    onClose();
  };

  const canSubmit =
    title.trim().length > 0 &&
    (taskType !== 'automated' || templateTitle.trim().length > 0);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!canSubmit || isSubmitting) return;

    setIsSubmitting(true);
    try {
      const assigneeUid = taskType === 'automated' ? undefined : employeeUid || undefined;
      const payload = {
        title: title.trim(),
        description: description.trim() || undefined,
        task_type: taskType,
        work_type: workType,
        employee_uid: assigneeUid,
        supervisor_uid: taskType === 'automated' ? undefined : supervisorUid || null,
        room_uid: taskType === 'automated' ? undefined : roomUid || null,
        washroom_uid: taskType === 'automated' ? undefined : washroomUid || null,
        zone_uid: zoneUid || null,
        priority,
        due_date: taskType === 'automated' ? undefined : dueDate || undefined,
        due_time: taskType === 'automated' ? undefined : dueTime || undefined,
        recurrence: taskType === 'repetitive' ? recurrence : undefined,
        start_time: taskType === 'repetitive' && startTime ? startTime : undefined,
        recurrence_window_end:
          taskType === 'repetitive' && windowEnd ? windowEnd : undefined,
        recurrence_start_date:
          taskType === 'repetitive' && runsFrom ? runsFrom : undefined,
        recurrence_end_date:
          taskType === 'repetitive' && !runsForever && runsUntil ? runsUntil : undefined,
        recurrence_interval_days:
          taskType === 'repetitive' && recurrence === 'custom'
            ? Math.max(1, parseInt(intervalDays) || 1)
            : undefined,
        automation_rule:
          taskType === 'automated'
            ? {
                trigger,
                scope_zone_uid: scopeZoneUid || null,
                template_title: templateTitle.trim(),
                template_description: templateDescription.trim() || undefined,
                assign_to_uid: ruleAssigneeUid || undefined,
              }
            : undefined,
      };

      if (isEdit && editTask) {
        await updateTask(editTask.task_uid, payload);
      } else {
        await createTask(payload);
      }

      handleClose();
    } catch {
      // Error toast handled by the context layer
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={handleClose}
      title={isEdit ? 'Edit Task' : 'Add Task'}
      description={
        isEdit
          ? `Editing ${editTask?.task_uid} in ${activeProperty?.name}`
          : `Create a task for ${activeProperty?.name}`
      }
      maxWidth="lg"
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Work Type — the domain kind; decides eligible departments */}
        <div>
          <label className={labelCls}>Work Type *</label>
          <div className="flex flex-wrap gap-2">
            {WORK_TYPE_OPTIONS.map((opt) => (
              <button
                key={opt.value}
                type="button"
                onClick={() => setWorkType(opt.value)}
                className={`px-3.5 py-2 rounded-[10px] border text-[13px] font-medium cursor-pointer transition-all ${
                  workType === opt.value
                    ? 'border-[#386641] bg-[#EBF3EC] text-[#244E2C] ring-1 ring-[#386641]/30'
                    : 'border-[#DDD7CB] bg-[#FAF8F5] text-[#555047] hover:bg-[#F2ECE3]'
                }`}
              >
                {opt.label}
              </button>
            ))}
          </div>
        </div>

        {/* Task Type selector */}
        <div>
          <label className={labelCls}>Task Type *</label>
          <div className="grid grid-cols-3 gap-2">
            {TYPE_OPTIONS.map((opt) => (
              <button
                key={opt.value}
                type="button"
                onClick={() => setTaskType(opt.value)}
                className={`p-3 rounded-[12px] border text-left transition-all cursor-pointer ${
                  taskType === opt.value
                    ? 'border-[#386641] bg-[#EBF3EC] ring-1 ring-[#386641]/30'
                    : 'border-[#DDD7CB] bg-[#FAF8F5] hover:bg-[#F2ECE3]'
                }`}
              >
                <span
                  className={`flex items-center gap-1.5 text-xs font-semibold ${
                    taskType === opt.value ? 'text-[#244E2C]' : 'text-[#555047]'
                  }`}
                >
                  {opt.icon}
                  {opt.label}
                </span>
                <span className="block text-[10px] text-[#736E65] mt-1 leading-tight">
                  {opt.hint}
                </span>
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className={labelCls}>
            {taskType === 'automated' ? 'Rule Name *' : 'Title *'}
          </label>
          <input
            type="text"
            required
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder={
              taskType === 'automated'
                ? 'e.g. Auto: bed turnover housekeeping'
                : 'e.g. Inspect AC filters in Room 204'
            }
            className={inputCls}
          />
        </div>

        <div>
          <label className={labelCls}>Description</label>
          <textarea
            rows={2}
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Specific checks, supplies needed, or guest notes…"
            className={inputCls}
          />
        </div>

        {/* Assignment — hidden for automated rules (assignee lives on the template) */}
        {taskType !== 'automated' && (
          <div className="space-y-3.5">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
              <div>
                <label className={labelCls}>Assign To (Employee)</label>
                <select
                  value={employeeUid}
                  onChange={(e) => setEmployeeUid(e.target.value)}
                  className={`${inputCls} cursor-pointer`}
                >
                  <option value="">Unassigned</option>
                  {currentPropertyEmployees.filter(isEmployeeAssignable).map((emp) => (
                    <option key={emp.employee_uid} value={emp.employee_uid}>
                      {emp.name} — {emp.job_title}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className={labelCls}>Supervisor</label>
                <select
                  value={supervisorUid}
                  onChange={(e) => setSupervisorUid(e.target.value)}
                  className={`${inputCls} cursor-pointer`}
                >
                  <option value="">None</option>
                  {currentPropertyEmployees
                    .filter(isEmployeeAssignable)
                    .filter((emp) => emp.employee_uid !== employeeUid)
                    .map((emp) => (
                      <option key={emp.employee_uid} value={emp.employee_uid}>
                        {emp.name} — {emp.job_title}
                      </option>
                    ))}
                </select>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5">
              <div>
                <label className={labelCls}>Zone</label>
                <select
                  value={zoneUid}
                  onChange={(e) => setZoneUid(e.target.value)}
                  className={`${inputCls} cursor-pointer`}
                >
                  <option value="">No zone</option>
                  {currentPropertyZones.map((z) => (
                    <option key={z.zone_uid} value={z.zone_uid}>
                      {z.name}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className={labelCls}>Related Room</label>
                <select
                  value={roomUid}
                  onChange={(e) => {
                    setRoomUid(e.target.value);
                    if (e.target.value) setWashroomUid('');
                  }}
                  className={`${inputCls} cursor-pointer`}
                >
                  <option value="">No room</option>
                  {currentPropertyRooms.map((r) => (
                    <option key={r.room_uid} value={r.room_uid}>
                      {r.room_number}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className={labelCls}>Related Washroom</label>
                <select
                  value={washroomUid}
                  onChange={(e) => {
                    setWashroomUid(e.target.value);
                    if (e.target.value) setRoomUid('');
                  }}
                  className={`${inputCls} cursor-pointer`}
                >
                  <option value="">No washroom</option>
                  {currentPropertyWashrooms.map((w) => (
                    <option key={w.washroom_uid} value={w.washroom_uid}>
                      {w.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>
        )}

        {/* Repetitive schedule */}
        {taskType === 'repetitive' && (
          <div className="p-3.5 rounded-[12px] bg-[#F2EFF9] border border-[#DDD5F0] space-y-3">
            <span className="text-xs font-semibold text-[#554388] uppercase tracking-wider flex items-center gap-1.5">
              <RefreshCw className="w-3.5 h-3.5" /> Recurrence Schedule
            </span>
            <div className="grid grid-cols-2 gap-3">
              <select
                value={recurrence}
                onChange={(e) => setRecurrence(e.target.value as RecurrenceSchedule)}
                className={`${inputCls} bg-white cursor-pointer`}
              >
                <option value="hourly">{RECURRENCE_LABELS.hourly}</option>
                <option value="every_2_hours">{RECURRENCE_LABELS.every_2_hours}</option>
                <option value="every_6_hours">{RECURRENCE_LABELS.every_6_hours}</option>
                <option value="every_12_hours">{RECURRENCE_LABELS.every_12_hours}</option>
                <option value="daily">{RECURRENCE_LABELS.daily}</option>
                <option value="weekly">{RECURRENCE_LABELS.weekly}</option>
                <option value="monthly">{RECURRENCE_LABELS.monthly}</option>
                <option value="custom">{RECURRENCE_LABELS.custom}</option>
              </select>
              {recurrence === 'custom' && (
                <div className="flex items-center gap-2">
                  <input
                    type="number"
                    min={1}
                    value={intervalDays}
                    onChange={(e) => setIntervalDays(e.target.value)}
                    className={`${inputCls} bg-white`}
                  />
                  <span className="text-xs text-[#554388] whitespace-nowrap">days</span>
                </div>
              )}
            </div>
            {/* Daily window — "every hour from 7 AM to 10 PM" */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-medium text-[#554388] mb-1">
                  From time
                </label>
                <input
                  type="time"
                  value={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  className={`${inputCls} bg-white`}
                  title="Time of day each occurrence begins"
                />
              </div>
              <div>
                <label className="block text-[11px] font-medium text-[#554388] mb-1">
                  Until time
                </label>
                <input
                  type="time"
                  value={windowEnd}
                  onChange={(e) => setWindowEnd(e.target.value)}
                  className={`${inputCls} bg-white`}
                  title="Hourly recurrences stop after this time and resume next day"
                />
              </div>
            </div>
            {['hourly', 'every_2_hours', 'every_6_hours', 'every_12_hours'].includes(recurrence) ? (
              <p className="text-[10px] text-[#7C76A0]">
                Occurrences run between From and Until each day, then resume next morning.
              </p>
            ) : (
              <p className="text-[10px] text-[#7C76A0]">
                Each generated occurrence starts at the From time.
              </p>
            )}

            {/* Run window — from date to end date, or forever */}
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-[11px] font-medium text-[#554388] mb-1">
                  Runs from
                </label>
                <input
                  type="date"
                  value={runsFrom}
                  onChange={(e) => setRunsFrom(e.target.value)}
                  className={`${inputCls} bg-white`}
                />
              </div>
              <div>
                <label className="block text-[11px] font-medium text-[#554388] mb-1">
                  Until
                </label>
                <input
                  type="date"
                  value={runsUntil}
                  onChange={(e) => setRunsUntil(e.target.value)}
                  disabled={runsForever}
                  className={`${inputCls} bg-white disabled:opacity-40`}
                />
              </div>
            </div>
            <label className="flex items-center gap-2 text-xs text-[#554388] cursor-pointer">
              <input
                type="checkbox"
                checked={runsForever}
                onChange={(e) => setRunsForever(e.target.checked)}
                className="accent-[#554388]"
              />
              Runs forever (no end date)
            </label>
          </div>
        )}

        {/* Automation rule builder */}
        {taskType === 'automated' && (
          <div className="p-3.5 rounded-[12px] bg-[#EFF0FA] border border-[#D5DAF0] space-y-3.5">
            <span className="text-xs font-semibold text-[#3F4C8C] uppercase tracking-wider flex items-center gap-1.5">
              <Zap className="w-3.5 h-3.5" /> Automation Rule
            </span>

            <div>
              <label className={labelCls}>Trigger Event *</label>
              <select
                value={trigger}
                onChange={(e) => setTrigger(e.target.value as AutomationTrigger)}
                className={`${inputCls} bg-white cursor-pointer`}
              >
                {(Object.keys(AUTOMATION_TRIGGER_LABELS) as AutomationTrigger[]).map((t) => (
                  <option key={t} value={t}>
                    When: {AUTOMATION_TRIGGER_LABELS[t]}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className={labelCls}>Scope</label>
              <select
                value={scopeZoneUid}
                onChange={(e) => setScopeZoneUid(e.target.value)}
                className={`${inputCls} bg-white cursor-pointer`}
              >
                <option value="">Entire property</option>
                {currentPropertyZones.map((z) => (
                  <option key={z.zone_uid} value={z.zone_uid}>
                    Only in {z.name}
                  </option>
                ))}
              </select>
            </div>

            <div className="pt-2 border-t border-[#D5DAF0]">
              <label className={labelCls}>Generated Task Template *</label>
              <input
                type="text"
                required={taskType === 'automated'}
                value={templateTitle}
                onChange={(e) => setTemplateTitle(e.target.value)}
                placeholder="e.g. Verify bed readiness after turnover"
                className={`${inputCls} bg-white`}
              />
              <textarea
                rows={2}
                value={templateDescription}
                onChange={(e) => setTemplateDescription(e.target.value)}
                placeholder="Instructions carried into each generated task…"
                className={`${inputCls} bg-white mt-2`}
              />
              <select
                value={ruleAssigneeUid}
                onChange={(e) => setRuleAssigneeUid(e.target.value)}
                className={`${inputCls} bg-white mt-2 cursor-pointer`}
              >
                <option value="">Generated tasks: unassigned</option>
                {currentPropertyEmployees.filter(isEmployeeAssignable).map((emp) => (
                  <option key={emp.employee_uid} value={emp.employee_uid}>
                    Always assign to {emp.name}
                  </option>
                ))}
              </select>
            </div>
          </div>
        )}

        {/* Due date + priority — not applicable to automation rules */}
        {taskType !== 'automated' && (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3.5">
            <div>
              <label className={labelCls}>Due Date</label>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className={inputCls}
              />
            </div>
            <div>
              <label className={labelCls}>Due Time</label>
              <input
                type="time"
                value={dueTime}
                onChange={(e) => setDueTime(e.target.value)}
                className={inputCls}
              />
            </div>
            <div className="col-span-2 sm:col-span-1">
              <label className={labelCls}>Priority</label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as TaskPriority)}
                className={`${inputCls} cursor-pointer`}
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>
          </div>
        )}

        <div className="flex items-center justify-end gap-3 pt-3 border-t border-[#F0ECE4]">
          <Button type="button" variant="outline" onClick={handleClose} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button type="submit" variant="primary" isLoading={isSubmitting} disabled={!canSubmit}>
            {isEdit ? 'Save Changes' : taskType === 'automated' ? 'Create Rule' : 'Create Task'}
          </Button>
        </div>
      </form>
    </Modal>
  );
};
