import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  Calendar,
  Camera,
  CheckCircle2,
  Clock,
  ImageIcon,
  Layers,
  Play,
  RefreshCw,
  Repeat2,
  Trash2,
  Undo2,
  UserCheck,
  User as UserIcon,
  Zap,
  Pencil,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import * as tasksApi from '../../api/tasks';
import { perfLog } from '../../dev/perf';
import { mediaUrl } from '../../api/client';
import { CompletionEvidenceLightbox, EvidenceImage } from './CompletionEvidenceLightbox';
import {
  ALLOWED_COMPLETION_IMAGE_TYPES,
  MAX_COMPLETION_IMAGES,
  MAX_UPLOAD_BYTES,
} from '../../lib/mediaLimits';
import { Drawer } from '../ui/Drawer';
import { Badge, TaskStatusBadge, TaskTypeBadge } from '../ui/Badge';
import { Button } from '../ui/Button';
import { ConfirmationDialog } from '../ui/ConfirmationDialog';
import { Task, TaskCompletionSubmission, TaskHistoryEvent } from '../../types';
import {
  AUTOMATION_TRIGGER_LABELS,
  RECURRENCE_LABELS,
  formatEventTime,
  formatTaskDue,
  getEffectiveTaskStatus,
} from '../../lib/taskUtils';
import { getInitials } from '../../lib/utils';
import { isEmployeeAssignable } from '../../lib/employeeUtils';

interface TaskDetailDrawerProps {
  task: Task | null;
  onClose: () => void;
  onEdit?: (task: Task) => void;
}

const EVENT_META: Record<
  TaskHistoryEvent['type'],
  { label: string; icon: React.ReactNode; dot: string }
> = {
  allocated: {
    label: 'Task allocated',
    icon: <UserCheck className="w-3.5 h-3.5" />,
    dot: 'bg-[#7C6DAF]',
  },
  auto_generated: {
    label: 'Auto-generated by rule',
    icon: <Zap className="w-3.5 h-3.5" />,
    dot: 'bg-[#7C6DAF]',
  },
  started: {
    label: 'Work started',
    icon: <Play className="w-3.5 h-3.5" />,
    dot: 'bg-[#D97706]',
  },
  submitted: {
    label: 'Submitted for review',
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#2563EB]',
  },
  approved: {
    label: 'Approved by supervisor',
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#386641]',
  },
  rejected: {
    label: 'Rejected by supervisor',
    icon: <Undo2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#C53B3B]',
  },
  reopened: {
    label: 'Task reopened',
    icon: <RefreshCw className="w-3.5 h-3.5" />,
    dot: 'bg-[#D97706]',
  },
  completed: {
    label: 'Marked complete',
    icon: <CheckCircle2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#386641]',
  },
  redo_requested: {
    label: 'Redo requested',
    icon: <Undo2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#C53B3B]',
  },
  reassigned: {
    label: 'Reassigned',
    icon: <Repeat2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#8C867C]',
  },
  edited: {
    label: 'Details edited',
    icon: <Pencil className="w-3.5 h-3.5" />,
    dot: 'bg-[#8C867C]',
  },
  evidence_deleted: {
    label: 'Evidence image deleted',
    icon: <Trash2 className="w-3.5 h-3.5" />,
    dot: 'bg-[#8C867C]',
  },
};

/** Evidence photo — hides itself entirely if the file can't be loaded
 *  (stale/deleted uploads must not render a broken-image icon). */
const EvidenceFigure: React.FC<{
  item: { image_uid?: string | null; photo: string; at: string; actor: string };
  onOpen: () => void;
}> = ({ item, onOpen }) => {
  const [failed, setFailed] = useState(false);
  if (failed) return null;
  return (
    <figure className="rounded-[12px] overflow-hidden border border-[#E4DFD5] bg-white">
      <button
        type="button"
        onClick={onOpen}
        className="block w-full cursor-zoom-in focus:outline-none focus:ring-2 focus:ring-[#386641]"
      >
        <img
          src={mediaUrl(item.photo)}
          alt={`Evidence by ${item.actor}`}
          className="w-full h-28 object-cover"
          onError={() => setFailed(true)}
        />
      </button>
      <figcaption className="px-2.5 py-1.5 text-[10px] text-[#6C675F] font-body">
        {item.actor} · {formatEventTime(item.at)}
      </figcaption>
    </figure>
  );
};

export const TaskDetailDrawer: React.FC<TaskDetailDrawerProps> = ({ task: taskSummary, onClose, onEdit }) => {
  const {
    currentUser,
    employees,
    zones,
    currentPropertyEmployees,
    completeTask,
    reopenTask,
    requestTaskRedo,
    reassignTask,
    deleteTask,
    addToast,
  } = useApp();

  /** Selected evidence photos — uploaded to POST /media/uploads on completion */
  const [evidencePhotos, setEvidencePhotos] = useState<{ file: File; previewUrl: string }[]>([]);
  const [completionNote, setCompletionNote] = useState('');
  const [redoMode, setRedoMode] = useState(false);
  const [redoNote, setRedoNote] = useState('');
  const [reassignMode, setReassignMode] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState(false);
  const [isCompleting, setIsCompleting] = useState(false);
  const [viewer, setViewer] = useState<{
    title: string;
    images: EvidenceImage[];
    index: number;
  } | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const evidencePhotosRef = useRef(evidencePhotos);
  evidencePhotosRef.current = evidencePhotos;

  // The tasks list is now a slim payload — history/images/submissions are
  // loaded on demand when a task is opened. The summary prop renders
  // instantly while the detail request is in flight; refetch when the
  // collection entry's lifecycle fields change (mutation refresh).
  const [taskDetail, setTaskDetail] = useState<Task | null>(null);
  useEffect(() => {
    setTaskDetail(null);
    const uid = taskSummary?.task_uid;
    if (!uid) return;
    perfLog(
      `[DETAIL] task=${uid.slice(0, 8)} status=${taskSummary?.status}` +
      ` submitted=${taskSummary?.submitted_at ?? '-'} emp=${taskSummary?.employee_uid?.slice(0, 8) ?? '-'}`
    );
    let live = true;
    void tasksApi.getTask(uid)
      .then((t) => { if (live) setTaskDetail(t); })
      .catch(() => {});
    return () => { live = false; };
  }, [
    taskSummary?.task_uid, taskSummary?.status, taskSummary?.submitted_at,
    taskSummary?.completed_at, taskSummary?.employee_uid,
  ]);
  const task = taskDetail ?? taskSummary;

  useEffect(
    () => () => evidencePhotosRef.current.forEach((photo) => URL.revokeObjectURL(photo.previewUrl)),
    []
  );

  const status = task ? getEffectiveTaskStatus(task) : 'pending';
  const canManage = currentUser?.role !== 'employee'; // PM & Super Admin share the same management actions

  const zone = zones.find((z) => z.zone_uid === task?.zone_uid);
  const assignee = employees.find(
    (e) => e.employee_uid === task?.employee_uid || e.employee_uid === task?.assigned_to_uid
  );

  const evidenceAttempts = useMemo((): TaskCompletionSubmission[] => {
    if (!task) return [];
    if (task.completion_submissions?.length) {
      return [...task.completion_submissions].sort(
        (a, b) => b.attempt_number - a.attempt_number
      );
    }
    const events = task.history.filter((h) => h.photos?.length);
    return [...events].reverse().map((event, index) => ({
      submission_uid: event.event_uid,
      task_uid: task.task_uid,
      event_uid: event.event_uid,
      attempt_number: events.length - index,
      employee_name: event.actor_name,
      submitted_at: event.at,
      status: index === 0 && task.status === 'submitted'
        ? 'pending'
        : event.type === 'completed' ? 'approved' : 'disapproved',
      reviewed_at: undefined,
      reviewed_by_name: undefined,
      review_comment: undefined,
      images: event.photos!.map((url) => ({ url })),
    }));
  }, [task]);

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0) return;
    const accepted = files.slice(
      0,
      Math.max(MAX_COMPLETION_IMAGES - evidencePhotos.length, 0)
    );
    if (files.length > accepted.length) {
      addToast({
        type: 'error',
        title: 'Too many photos',
        description: `A submission can include at most ${MAX_COMPLETION_IMAGES} images.`,
      });
    }
    accepted.forEach((file) => {
      if (!ALLOWED_COMPLETION_IMAGE_TYPES.has(file.type)) {
        addToast({
          type: 'error',
          title: 'Photo upload failed',
          description: `${file.name} must be a JPEG, PNG, WebP, or HEIC image.`,
        });
        return;
      }
      if (file.size > MAX_UPLOAD_BYTES) {
        addToast({
          type: 'error',
          title: 'Photo upload failed',
          description: `${file.name} exceeds the 10 MB limit.`,
        });
        return;
      }
      setEvidencePhotos((prev) => [
        ...prev,
        { file, previewUrl: URL.createObjectURL(file) },
      ]);
    });
    e.target.value = '';
  };

  const resetLocal = () => {
    setEvidencePhotos((prev) => {
      prev.forEach((p) => URL.revokeObjectURL(p.previewUrl));
      return [];
    });
    setCompletionNote('');
    setRedoMode(false);
    setRedoNote('');
    setReassignMode(false);
  };

  const handleClose = () => {
    resetLocal();
    onClose();
  };

  const handleComplete = async () => {
    if (!task || isCompleting) return;
    setIsCompleting(true);
    try {
      await completeTask(
        task.task_uid,
        evidencePhotos.map((p) => p.file),
        completionNote.trim() || undefined
      );
      resetLocal();
    } catch (err) {
      addToast({
        type: 'error',
        title: 'Upload Failed',
        description: err instanceof Error ? err.message : 'Could not upload evidence photos.',
      });
    } finally {
      setIsCompleting(false);
    }
  };

  const timeline = useMemo(() => {
    if (!task?.history) return [];
    return [...task.history].reverse(); // newest first
  }, [task]);

  return (
    <>
      <Drawer
        isOpen={!!task}
        onClose={handleClose}
        title={task?.title || 'Task'}
        description={
          task
            ? `${task.ticket_number || task.task_uid} · Created by ${task.created_by_name || 'System'}`
            : undefined
        }
      >
        {task && (
          <div className="space-y-6">
            {/* Status row */}
            <div className="flex items-center gap-2 flex-wrap">
              <TaskStatusBadge status={status} size="md" />
              <TaskTypeBadge type={task.task_type} size="md" />
              <Badge
                size="md"
                variant={
                  task.priority === 'urgent'
                    ? 'red'
                    : task.priority === 'high'
                    ? 'orange'
                    : task.priority === 'medium'
                    ? 'lavender'
                    : 'neutral'
                }
              >
                {task.priority} priority
              </Badge>
            </div>

            {/* Description */}
            {task.description && (
              <p className="text-sm text-[#4B4741] font-body leading-relaxed">{task.description}</p>
            )}

            {/* Meta grid */}
            <div className="grid grid-cols-2 gap-2.5">
              <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                  <UserIcon className="w-3 h-3" /> Assigned To
                </span>
                <div className="flex items-center gap-2 mt-1.5">
                  {assignee ? (
                    <>
                      <span
                        className="w-6 h-6 rounded-full text-white text-[10px] font-bold flex items-center justify-center shrink-0"
                        style={{ backgroundColor: assignee.avatar_color || '#386641' }}
                      >
                        {getInitials(assignee.name)}
                      </span>
                      <span className="text-xs font-medium text-[#24221F] truncate">
                        {assignee.name}
                      </span>
                    </>
                  ) : (
                    <span className="text-xs text-[#8C867C]">Unassigned</span>
                  )}
                </div>
              </div>

              <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                  <UserCheck className="w-3 h-3" /> Supervisor
                </span>
                <p className="text-xs font-medium text-[#24221F] mt-1.5 truncate">
                  {task.supervisor_name || '—'}
                </p>
              </div>

              <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                  <Layers className="w-3 h-3" /> Zone
                </span>
                <p className="text-xs font-medium text-[#24221F] mt-1.5 truncate">
                  {zone?.name || 'No zone assigned'}
                </p>
              </div>

              {(task.room_number || task.dorm_name || task.washroom_name) && (
                <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                  <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                    <Layers className="w-3 h-3" /> Resource
                  </span>
                  <p className="text-xs font-medium text-[#24221F] mt-1.5 truncate">
                    {task.room_number || task.dorm_name || task.washroom_name}
                  </p>
                </div>
              )}

              <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                  <Calendar className="w-3 h-3" /> Due
                </span>
                <p className="text-xs font-medium text-[#24221F] mt-1.5">{formatTaskDue(task)}</p>
              </div>

              <div className="p-3 rounded-[12px] bg-white border border-[#EAE5DC]">
                <span className="text-[10px] font-semibold text-[#8C867C] uppercase tracking-wider flex items-center gap-1">
                  <Clock className="w-3 h-3" /> Schedule
                </span>
                <p className="text-xs font-medium text-[#24221F] mt-1.5">
                  {task.task_type === 'repetitive'
                    ? `Repeats: ${RECURRENCE_LABELS[task.recurrence || 'daily']}${
                        task.recurrence === 'custom' && task.recurrence_interval_days
                          ? ` (every ${task.recurrence_interval_days} days)`
                          : ''
                      }`
                    : task.task_type === 'automated'
                    ? 'Runs on trigger'
                    : 'One-time'}
                </p>
              </div>
            </div>

            {/* Automation rule summary */}
            {task.task_type === 'automated' && task.automation_rule && (
              <div className="p-4 rounded-[14px] bg-[#F2EFF9] border border-[#DDD5F0]">
                <div className="flex items-center gap-2 mb-2">
                  <Zap className="w-4 h-4 text-[#554388]" />
                  <h4 className="font-display font-semibold text-sm text-[#3F3370]">
                    Automation Rule
                  </h4>
                </div>
                <dl className="text-xs text-[#4B4272] space-y-1.5 font-body">
                  <div className="flex gap-2">
                    <dt className="font-semibold shrink-0 w-20">Trigger</dt>
                    <dd>{AUTOMATION_TRIGGER_LABELS[task.automation_rule.trigger]}</dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="font-semibold shrink-0 w-20">Scope</dt>
                    <dd>
                      {task.automation_rule.scope_zone_uid
                        ? zones.find((z) => z.zone_uid === task.automation_rule?.scope_zone_uid)
                            ?.name || 'Specific zone'
                        : 'Entire property'}
                    </dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="font-semibold shrink-0 w-20">Generates</dt>
                    <dd>“{task.automation_rule.template_title}”</dd>
                  </div>
                </dl>
              </div>
            )}

            {evidenceAttempts.length > 0 && (
              <div>
                <h4 className="font-display font-semibold text-sm text-[#24221F] flex items-center gap-2 mb-2.5">
                  <ImageIcon className="w-4 h-4 text-[#386641]" />
                  Completion Evidence
                </h4>
                <div className="space-y-3">
                  {evidenceAttempts.map((attempt) => (
                    <div
                      key={attempt.submission_uid}
                      className={`rounded-[12px] border p-3 ${
                        attempt.status === 'pending'
                          ? 'border-[#B7CFAA] bg-[#F7FAF4]'
                          : 'border-[#E4DFD5] bg-[#FAF8F5]'
                      }`}
                    >
                      <div className="flex items-center justify-between gap-2 flex-wrap">
                        <div>
                          <p className="text-xs font-semibold text-[#24221F]">
                            Attempt {attempt.attempt_number} · {attempt.images.length} image{attempt.images.length === 1 ? '' : 's'}
                          </p>
                          <p className="text-[11px] text-[#6C675F] mt-0.5">
                            {attempt.employee_name || 'Unknown'} · {attempt.submitted_at ? formatEventTime(attempt.submitted_at) : '—'}
                          </p>
                          {attempt.reviewed_at && (
                            <p className="text-[11px] text-[#6C675F] mt-0.5">
                              Reviewed{attempt.reviewed_by_name ? ` by ${attempt.reviewed_by_name}` : ''} · {formatEventTime(attempt.reviewed_at)}
                            </p>
                          )}
                        </div>
                        <Badge
                          variant={attempt.status === 'approved' ? 'sage' : attempt.status === 'disapproved' ? 'red' : 'orange'}
                          size="sm"
                        >
                          {attempt.status === 'approved'
                            ? 'Approved'
                            : attempt.status === 'disapproved'
                              ? 'Disapproved'
                              : 'Pending Review'}
                        </Badge>
                      </div>
                      {attempt.review_comment && (
                        <p className="mt-2 text-[11px] text-[#555047] bg-white border border-[#EDE8DE] rounded-[8px] px-2.5 py-1.5">
                          Review: {attempt.review_comment}
                        </p>
                      )}
                      {attempt.images.length > 0 ? (
                        <div className="grid grid-cols-2 gap-2.5 mt-2.5">
                          {attempt.images.map((image, i) => (
                            <EvidenceFigure
                              key={image.image_uid || `${attempt.submission_uid}-${i}`}
                              item={{
                                image_uid: image.image_uid,
                                photo: image.url,
                                at: image.created_at || attempt.submitted_at || task.created_at || '',
                                actor: image.created_by_name || attempt.employee_name || 'Unknown',
                              }}
                              onOpen={() => setViewer({
                                title: `Completion Evidence — Attempt ${attempt.attempt_number}`,
                                images: attempt.images,
                                index: i,
                              })}
                            />
                          ))}
                        </div>
                      ) : (
                        <p className="mt-2 text-[11px] text-[#8A857B]">
                          No images remain in this submission
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* History timeline */}
            <div>
              <h4 className="font-display font-semibold text-sm text-[#24221F] flex items-center gap-2 mb-3">
                <Clock className="w-4 h-4 text-[#736E65]" />
                Task History
              </h4>
              <ol className="relative border-l border-[#E4DFD5] ml-2 space-y-4">
                {timeline.map((event) => {
                  const meta = EVENT_META[event.type] || EVENT_META.allocated;
                  return (
                    <li key={event.event_uid} className="ml-5 relative">
                      <span
                        className={`absolute -left-[27px] top-0.5 w-5 h-5 rounded-full ${meta.dot} text-white flex items-center justify-center ring-4 ring-[#FAF8F5]`}
                      >
                        {meta.icon}
                      </span>
                      <div>
                        <p className="text-xs font-semibold text-[#24221F]">{meta.label}</p>
                        <p className="text-[11px] text-[#736E65] font-body">
                          {event.actor_name} · {formatEventTime(event.at)}
                        </p>
                        {event.note && (
                          <p className="text-[11px] text-[#555047] font-body mt-0.5 bg-white border border-[#EDE8DF] rounded-[8px] px-2 py-1 inline-block">
                            {event.note}
                          </p>
                        )}
                        {event.photos && event.photos.length > 0 && (
                          <div className="flex gap-1.5 mt-1.5">
                            {event.photos.map((p, i) => (
                              <img
                                key={i}
                                src={mediaUrl(p)}
                                alt="evidence"
                                className="w-12 h-12 rounded-[8px] object-cover border border-[#E4DFD5]"
                              />
                            ))}
                          </div>
                        )}
                      </div>
                    </li>
                  );
                })}
              </ol>
            </div>

            {/* Completion — photo evidence mandatory */}
            {canManage && !['completed', 'cancelled', 'submitted'].includes(status) && (
              <div className="p-4 rounded-[14px] bg-white border border-[#E4DFD5] space-y-3">
                <h4 className="font-display font-semibold text-sm text-[#24221F]">
                  Complete task
                </h4>
                <p className="text-[11px] text-[#6C675F] font-body">
                  Attach at least one photo of the finished work — it will be stored in the task
                  history as evidence.
                </p>

                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/jpeg,image/png,image/webp,image/heic,image/heif"
                  multiple
                  className="hidden"
                  onChange={handlePhotoUpload}
                />
                <div className="flex items-center gap-2 flex-wrap">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => fileInputRef.current?.click()}
                    className="gap-1.5"
                  >
                    <Camera className="w-3.5 h-3.5" />
                    <span>Add Photos</span>
                  </Button>
                  {evidencePhotos.length === 0 ? (
                    <span className="text-[11px] text-[#A34A07] font-medium">
                      Required before completing
                    </span>
                  ) : (
                    <span className="text-[11px] text-[#6C675F] font-medium">
                      {evidencePhotos.length} photo{evidencePhotos.length > 1 ? 's' : ''} selected
                      · max {MAX_COMPLETION_IMAGES}
                    </span>
                  )}
                </div>

                {evidencePhotos.length > 0 && (
                  <div className="flex gap-2 flex-wrap">
                    {evidencePhotos.map((p, i) => (
                      <div key={i} className="relative">
                        <img
                          src={p.previewUrl}
                          alt={`evidence ${i + 1}`}
                          className="w-16 h-16 rounded-[10px] object-cover border border-[#DDD7CB]"
                        />
                        <button
                          type="button"
                          onClick={() =>
                            setEvidencePhotos((prev) => {
                              const next = prev.filter((_, idx) => idx !== i);
                              URL.revokeObjectURL(prev[i].previewUrl);
                              return next;
                            })
                          }
                          className="absolute -top-1.5 -right-1.5 w-5 h-5 bg-[#C53B3B] text-white rounded-full text-[10px] leading-none flex items-center justify-center cursor-pointer"
                          title="Remove photo"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                )}

                <input
                  type="text"
                  value={completionNote}
                  onChange={(e) => setCompletionNote(e.target.value)}
                  placeholder="Completion note (optional)"
                  className="w-full px-3 py-2 bg-[#FAF8F5] border border-[#DDD7CB] rounded-[10px] text-xs text-[#24221F] focus:outline-none focus:ring-2 focus:ring-[#386641]"
                />

                <div className="flex items-center gap-2 pt-1">
                  <Button
                    variant="primary"
                    size="sm"
                    disabled={evidencePhotos.length === 0 || isCompleting}
                    isLoading={isCompleting}
                    onClick={handleComplete}
                    title={
                      evidencePhotos.length === 0
                        ? 'Attach at least one photo to enable completion'
                        : 'Mark the task as completed'
                    }
                    className="gap-1.5"
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Mark Complete</span>
                  </Button>
                </div>
              </div>
            )}

            {/* Manager / Admin actions */}
            {canManage && (
              <div className="p-4 rounded-[14px] bg-white border border-[#E4DFD5] space-y-3">
                <h4 className="font-display font-semibold text-sm text-[#24221F]">
                  Management Actions
                </h4>

                <div className="flex items-center gap-2 flex-wrap">
                  {['completed', 'cancelled'].includes(status) && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => reopenTask(task.task_uid)}
                      className="gap-1.5 text-[#9A4C07] border-[#E5C9A8] hover:bg-[#FEF3E8]"
                    >
                      <RefreshCw className="w-3.5 h-3.5" />
                      <span>Reopen</span>
                    </Button>
                  )}
                  {status === 'completed' && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setRedoMode((v) => !v)}
                      className="gap-1.5 text-[#9A4C07] border-[#E5C9A8] hover:bg-[#FEF3E8]"
                    >
                      <Undo2 className="w-3.5 h-3.5" />
                      <span>Request Redo</span>
                    </Button>
                  )}
                  {task.task_type !== 'automated' && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setReassignMode((v) => !v)}
                      className="gap-1.5"
                    >
                      <Repeat2 className="w-3.5 h-3.5" />
                      <span>Reassign</span>
                    </Button>
                  )}
                  {onEdit && (
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => onEdit(task)}
                      className="gap-1.5"
                    >
                      <Pencil className="w-3.5 h-3.5" />
                      <span>Edit</span>
                    </Button>
                  )}
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setDeleteConfirm(true)}
                    className="gap-1.5 text-[#A32A2A] border-[#F0C4C4] hover:bg-[#FDE8E8]"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    <span>Delete</span>
                  </Button>
                </div>

                {redoMode && (
                  <div className="space-y-2 pt-1">
                    <textarea
                      rows={2}
                      value={redoNote}
                      onChange={(e) => setRedoNote(e.target.value)}
                      placeholder="Why does this need to be redone?"
                      className="w-full px-3 py-2 bg-[#FAF8F5] border border-[#DDD7CB] rounded-[10px] text-xs text-[#24221F] focus:outline-none focus:ring-2 focus:ring-[#386641]"
                    />
                    <div className="flex gap-2">
                      <Button
                        size="sm"
                        variant="primary"
                        onClick={() => {
                          requestTaskRedo(task.task_uid, redoNote.trim() || undefined);
                          setRedoMode(false);
                          setRedoNote('');
                        }}
                      >
                        Confirm Redo Request
                      </Button>
                      <Button size="sm" variant="ghost" onClick={() => setRedoMode(false)}>
                        Cancel
                      </Button>
                    </div>
                  </div>
                )}

                {reassignMode && (
                  <div className="space-y-2 pt-1">
                    <select
                      defaultValue=""
                      onChange={(e) => {
                        if (e.target.value) {
                          reassignTask(task.task_uid, e.target.value);
                          setReassignMode(false);
                        }
                      }}
                      className="w-full px-3 py-2 bg-[#FAF8F5] border border-[#DDD7CB] rounded-[10px] text-xs text-[#24221F] focus:outline-none focus:ring-2 focus:ring-[#386641] cursor-pointer"
                    >
                      <option value="" disabled>
                        Select new assignee…
                      </option>
                      {currentPropertyEmployees.filter(isEmployeeAssignable).map((emp) => (
                        <option key={emp.employee_uid} value={emp.employee_uid}>
                          {emp.name} — {emp.job_title}
                        </option>
                      ))}
                    </select>
                    <Button size="sm" variant="ghost" onClick={() => setReassignMode(false)}>
                      Cancel
                    </Button>
                  </div>
                )}
              </div>
            )}
          </div>
        )}
      </Drawer>

      {task && viewer && (
        <CompletionEvidenceLightbox
          images={viewer.images}
          initialIndex={viewer.index}
          title={viewer.title}
          onClose={() => setViewer(null)}
        />
      )}

      <ConfirmationDialog
        isOpen={deleteConfirm}
        onClose={() => setDeleteConfirm(false)}
        onConfirm={() => {
          if (task) {
            deleteTask(task.task_uid);
            handleClose();
          }
        }}
        entityType="Task"
        entityName={task?.title || ''}
        impactMessage="The task and its full history — including any photo evidence — will be permanently removed."
      />
    </>
  );
};
