"""maintenance dorm and bed targets

Revision ID: 027058f5a060
Revises: 649b374bfc29
Create Date: 2026-09-23 15:19:08.451899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027058f5a060'
down_revision: Union[str, Sequence[str], None] = '649b374bfc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_tickets', sa.Column('dorm_id', sa.Uuid(), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('dorm_name', sa.String(length=255), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('bed_id', sa.Uuid(), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('bed_number', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_maintenance_tickets_bed_id'), 'maintenance_tickets', ['bed_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_dorm_id'), 'maintenance_tickets', ['dorm_id'], unique=False)
    op.create_foreign_key('fk_maintenance_tickets_bed_id', 'maintenance_tickets', 'beds', ['bed_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_maintenance_tickets_dorm_id', 'maintenance_tickets', 'dorms', ['dorm_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('fk_maintenance_tickets_bed_id', 'maintenance_tickets', type_='foreignkey')
    op.drop_constraint('fk_maintenance_tickets_dorm_id', 'maintenance_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_tickets_dorm_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_bed_id'), table_name='maintenance_tickets')
    op.drop_column('maintenance_tickets', 'bed_number')
    op.drop_column('maintenance_tickets', 'bed_id')
    op.drop_column('maintenance_tickets', 'dorm_name')
    op.drop_column('maintenance_tickets', 'dorm_id')
    # ### end Alembic commands ###
