"""add workspace entities: properties areas zones rooms dorms beds employees tasks task_history

Revision ID: 345d9736662b
Revises: e01da4bc153a
Create Date: 2026-09-23 12:29:46.656336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345d9736662b'
down_revision: Union[str, Sequence[str], None] = 'e01da4bc153a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manager_employee_id', sa.Uuid(), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=False),
    sa.Column('manager_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_company_id'), 'properties', ['company_id'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_property_id'), 'areas', ['property_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('zone_type', sa.String(length=32), nullable=False),
    sa.Column('floor', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_area_id'), 'zones', ['area_id'], unique=False)
    op.create_index(op.f('ix_zones_property_id'), 'zones', ['property_id'], unique=False)
    op.create_table('dorms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dorm_type', sa.String(length=32), nullable=False),
    sa.Column('washroom', sa.String(length=32), nullable=False),
    sa.Column('floor', sa.String(length=100), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dorms_property_id'), 'dorms', ['property_id'], unique=False)
    op.create_index(op.f('ix_dorms_zone_id'), 'dorms', ['zone_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('salary', sa.String(length=64), nullable=True),
    sa.Column('shift', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(length=32), nullable=True),
    sa.Column('avatar_color', sa.String(length=16), nullable=True),
    sa.Column('leave_balance_days', sa.Integer(), nullable=True),
    sa.Column('leave_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index(op.f('ix_employees_property_id'), 'employees', ['property_id'], unique=False)
    op.create_index(op.f('ix_employees_zone_id'), 'employees', ['zone_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bed_count', sa.Integer(), nullable=False),
    sa.Column('cleaning_note', sa.String(length=500), nullable=True),
    sa.Column('current_guest', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_property_id'), 'rooms', ['property_id'], unique=False)
    op.create_index(op.f('ix_rooms_zone_id'), 'rooms', ['zone_id'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dorm_id', sa.Uuid(), nullable=False),
    sa.Column('bed_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dorm_id'], ['dorms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beds_dorm_id'), 'beds', ['dorm_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.String(length=64), nullable=True),
    sa.Column('due_time', sa.String(length=16), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('recurrence', sa.String(length=32), nullable=True),
    sa.Column('recurrence_interval_days', sa.Integer(), nullable=True),
    sa.Column('automation_rule', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_employee_id'), 'tasks', ['employee_id'], unique=False)
    op.create_index(op.f('ix_tasks_property_id'), 'tasks', ['property_id'], unique=False)
    op.create_index(op.f('ix_tasks_zone_id'), 'tasks', ['zone_id'], unique=False)
    op.create_table('task_history_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_history_events_task_id'), 'task_history_events', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_events_task_id'), table_name='task_history_events')
    op.drop_table('task_history_events')
    op.drop_index(op.f('ix_tasks_zone_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_property_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_employee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_beds_dorm_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_rooms_zone_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_property_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_employees_zone_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_property_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_dorms_zone_id'), table_name='dorms')
    op.drop_index(op.f('ix_dorms_property_id'), table_name='dorms')
    op.drop_table('dorms')
    op.drop_index(op.f('ix_zones_property_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_area_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_areas_property_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_properties_company_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
