"""maintenance tickets + task ticket fields

Revision ID: 649b374bfc29
Revises: a38d5c90adfd
Create Date: 2026-09-23 14:10:17.400848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '649b374bfc29'
down_revision: Union[str, Sequence[str], None] = 'a38d5c90adfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ticket number sequences — collision-safe server-side generation
    op.execute("CREATE SEQUENCE IF NOT EXISTS maintenance_ticket_seq")
    op.execute("CREATE SEQUENCE IF NOT EXISTS task_ticket_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=True),
    sa.Column('room_number', sa.String(length=32), nullable=True),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('reported_by_name', sa.String(length=255), nullable=True),
    sa.Column('maintenance_type', sa.String(length=64), nullable=False),
    sa.Column('issue', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('assigned_to_name', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.String(length=4000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tickets_assigned_to'), 'maintenance_tickets', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_company_id'), 'maintenance_tickets', ['company_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_property_id'), 'maintenance_tickets', ['property_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_room_id'), 'maintenance_tickets', ['room_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_status'), 'maintenance_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_ticket_number'), 'maintenance_tickets', ['ticket_number'], unique=True)
    op.create_table('maintenance_ticket_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['maintenance_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_ticket_attachments_ticket_id'), 'maintenance_ticket_attachments', ['ticket_id'], unique=False)
    op.create_table('maintenance_ticket_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['maintenance_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_ticket_events_ticket_id'), 'maintenance_ticket_events', ['ticket_id'], unique=False)
    op.add_column('tasks', sa.Column('ticket_number', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('room_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('room_number', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('supervisor_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('supervisor_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_room_id'), 'tasks', ['room_id'], unique=False)
    op.create_index(op.f('ix_tasks_supervisor_id'), 'tasks', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_tasks_ticket_number'), 'tasks', ['ticket_number'], unique=True)
    op.create_foreign_key('fk_tasks_room_id', 'tasks', 'rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_tasks_supervisor_id', 'tasks', 'employees', ['supervisor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS maintenance_ticket_seq")
    op.execute("DROP SEQUENCE IF EXISTS task_ticket_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tasks_room_id', 'tasks', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tasks_room_id', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_ticket_number'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_supervisor_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_room_id'), table_name='tasks')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'submitted_at')
    op.drop_column('tasks', 'supervisor_name')
    op.drop_column('tasks', 'supervisor_id')
    op.drop_column('tasks', 'room_number')
    op.drop_column('tasks', 'room_id')
    op.drop_column('tasks', 'ticket_number')
    op.drop_index(op.f('ix_maintenance_ticket_events_ticket_id'), table_name='maintenance_ticket_events')
    op.drop_table('maintenance_ticket_events')
    op.drop_index(op.f('ix_maintenance_ticket_attachments_ticket_id'), table_name='maintenance_ticket_attachments')
    op.drop_table('maintenance_ticket_attachments')
    op.drop_index(op.f('ix_maintenance_tickets_ticket_number'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_status'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_room_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_property_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_company_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_assigned_to'), table_name='maintenance_tickets')
    op.drop_table('maintenance_tickets')
    # ### end Alembic commands ###
