"""task recurrence window

Revision ID: 6920e7a5283e
Revises: db39ee38a729
Create Date: 2026-09-23 17:14:32.757035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6920e7a5283e'
down_revision: Union[str, Sequence[str], None] = 'db39ee38a729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recurrence_start_date', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_end_date', sa.String(length=64), nullable=True))
    op.add_column('tasks', sa.Column('recurrence_window_end', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence_window_end')
    op.drop_column('tasks', 'recurrence_end_date')
    op.drop_column('tasks', 'recurrence_start_date')
    # ### end Alembic commands ###
