"""task start_time

Revision ID: 6b2a1a12ad65
Revises: f0ac59d056c6
Create Date: 2026-09-23 16:30:45.831678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2a1a12ad65'
down_revision: Union[str, Sequence[str], None] = 'f0ac59d056c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###
