"""structure fields + allocation_events + unique constraints

Revision ID: a38d5c90adfd
Revises: 345d9736662b
Create Date: 2026-09-23 13:08:22.394090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38d5c90adfd'
down_revision: Union[str, Sequence[str], None] = '345d9736662b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('from_zone_id', sa.Uuid(), nullable=True),
    sa.Column('to_zone_id', sa.Uuid(), nullable=True),
    sa.Column('from_area_id', sa.Uuid(), nullable=True),
    sa.Column('to_area_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_events_entity_id'), 'allocation_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_allocation_events_entity_type'), 'allocation_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_allocation_events_property_id'), 'allocation_events', ['property_id'], unique=False)
    op.add_column('areas', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('areas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_areas_property_name', 'areas', ['property_id', 'name'])
    op.add_column('beds', sa.Column('property_id', sa.Uuid(), nullable=True))
    op.add_column('beds', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_beds_property_id'), 'beds', ['property_id'], unique=False)
    op.create_unique_constraint('uq_beds_dorm_number', 'beds', ['dorm_id', 'bed_number'])
    op.create_foreign_key('fk_beds_property_id', 'beds', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.add_column('dorms', sa.Column('area_id', sa.Uuid(), nullable=True))
    op.add_column('dorms', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('dorms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_dorms_area_id'), 'dorms', ['area_id'], unique=False)
    op.create_foreign_key('fk_dorms_area_id', 'dorms', 'areas', ['area_id'], ['id'], ondelete='SET NULL')
    op.add_column('rooms', sa.Column('area_id', sa.Uuid(), nullable=True))
    op.add_column('rooms', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_rooms_area_id'), 'rooms', ['area_id'], unique=False)
    op.create_unique_constraint('uq_rooms_property_number', 'rooms', ['property_id', 'room_number'])
    op.create_foreign_key('fk_rooms_area_id', 'rooms', 'areas', ['area_id'], ['id'], ondelete='SET NULL')
    op.add_column('zones', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('zones', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('zones', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint('uq_zones_property_name', 'zones', ['property_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_zones_property_name', 'zones', type_='unique')
    op.drop_column('zones', 'updated_at')
    op.drop_column('zones', 'display_order')
    op.drop_column('zones', 'status')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_rooms_area_id', 'rooms', type_='foreignkey')
    op.drop_constraint('uq_rooms_property_number', 'rooms', type_='unique')
    op.drop_index(op.f('ix_rooms_area_id'), table_name='rooms')
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'display_order')
    op.drop_column('rooms', 'area_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_dorms_area_id', 'dorms', type_='foreignkey')
    op.drop_index(op.f('ix_dorms_area_id'), table_name='dorms')
    op.drop_column('dorms', 'updated_at')
    op.drop_column('dorms', 'status')
    op.drop_column('dorms', 'area_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_beds_property_id', 'beds', type_='foreignkey')
    op.drop_constraint('uq_beds_dorm_number', 'beds', type_='unique')
    op.drop_index(op.f('ix_beds_property_id'), table_name='beds')
    op.drop_column('beds', 'updated_at')
    op.drop_column('beds', 'property_id')
    op.drop_constraint('uq_areas_property_name', 'areas', type_='unique')
    op.drop_column('areas', 'updated_at')
    op.drop_column('areas', 'status')
    op.drop_index(op.f('ix_allocation_events_property_id'), table_name='allocation_events')
    op.drop_index(op.f('ix_allocation_events_entity_type'), table_name='allocation_events')
    op.drop_index(op.f('ix_allocation_events_entity_id'), table_name='allocation_events')
    op.drop_table('allocation_events')
    # ### end Alembic commands ###
