"""work templates

Revision ID: db39ee38a729
Revises: 6b2a1a12ad65
Create Date: 2026-09-23 16:42:18.700056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db39ee38a729'
down_revision: Union[str, Sequence[str], None] = '6b2a1a12ad65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('assignment', sa.JSON(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('overdue', sa.JSON(), nullable=False),
    sa.Column('notifications', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_templates_company_id'), 'work_templates', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_templates_next_run_at'), 'work_templates', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_work_templates_property_id'), 'work_templates', ['property_id'], unique=False)
    op.create_index(op.f('ix_work_templates_status'), 'work_templates', ['status'], unique=False)
    op.create_index(op.f('ix_work_templates_template_type'), 'work_templates', ['template_type'], unique=False)
    op.create_table('template_generations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_key', sa.String(length=128), nullable=False),
    sa.Column('ticket_kind', sa.String(length=24), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=True),
    sa.Column('target_label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['work_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'occurrence_key', name='uq_template_generation')
    )
    op.create_index(op.f('ix_template_generations_template_id'), 'template_generations', ['template_id'], unique=False)
    op.create_table('work_template_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['work_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_version')
    )
    op.create_index(op.f('ix_work_template_versions_template_id'), 'work_template_versions', ['template_id'], unique=False)
    op.add_column('maintenance_tickets', sa.Column('template_id', sa.Uuid(), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('template_version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_maintenance_tickets_template_id'), 'maintenance_tickets', ['template_id'], unique=False)
    op.create_foreign_key('fk_maintenance_tickets_template', 'maintenance_tickets', 'work_templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('template_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('template_version', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_template_id'), 'tasks', ['template_id'], unique=False)
    op.create_foreign_key('fk_tasks_template', 'tasks', 'work_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_tasks_template', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_template_id'), table_name='tasks')
    op.drop_column('tasks', 'template_version')
    op.drop_column('tasks', 'template_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_maintenance_tickets_template', 'maintenance_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_tickets_template_id'), table_name='maintenance_tickets')
    op.drop_column('maintenance_tickets', 'template_version')
    op.drop_column('maintenance_tickets', 'template_id')
    op.drop_index(op.f('ix_work_template_versions_template_id'), table_name='work_template_versions')
    op.drop_table('work_template_versions')
    op.drop_index(op.f('ix_template_generations_template_id'), table_name='template_generations')
    op.drop_table('template_generations')
    op.drop_index(op.f('ix_work_templates_template_type'), table_name='work_templates')
    op.drop_index(op.f('ix_work_templates_status'), table_name='work_templates')
    op.drop_index(op.f('ix_work_templates_property_id'), table_name='work_templates')
    op.drop_index(op.f('ix_work_templates_next_run_at'), table_name='work_templates')
    op.drop_index(op.f('ix_work_templates_company_id'), table_name='work_templates')
    op.drop_table('work_templates')
    # ### end Alembic commands ###
