"""work allocation engine

Revision ID: f0ac59d056c6
Revises: 027058f5a060
Create Date: 2026-09-23 15:56:12.536097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ac59d056c6'
down_revision: Union[str, Sequence[str], None] = '027058f5a060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_allocation_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('last_assigned_employee_id', sa.Uuid(), nullable=True),
    sa.Column('last_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', name='uq_zone_allocation_state_zone')
    )
    op.create_index(op.f('ix_zone_allocation_state_property_id'), 'zone_allocation_state', ['property_id'], unique=False)
    op.create_index(op.f('ix_zone_allocation_state_zone_id'), 'zone_allocation_state', ['zone_id'], unique=False)
    op.create_table('work_allocation_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_number', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('zone_name', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=24), nullable=False),
    sa.Column('allocation_status', sa.String(length=32), nullable=False),
    sa.Column('allocation_reason', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_allocation_batches_batch_number'), 'work_allocation_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_work_allocation_batches_company_id'), 'work_allocation_batches', ['company_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_batches_employee_id'), 'work_allocation_batches', ['employee_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_batches_property_id'), 'work_allocation_batches', ['property_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_batches_zone_id'), 'work_allocation_batches', ['zone_id'], unique=False)
    op.create_table('work_allocation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('batch_number', sa.String(length=32), nullable=True),
    sa.Column('ticket_kind', sa.String(length=24), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('ticket_number', sa.String(length=32), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('previous_employee_id', sa.Uuid(), nullable=True),
    sa.Column('previous_employee_name', sa.String(length=255), nullable=True),
    sa.Column('allocation_method', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['work_allocation_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_allocation_history_batch_id'), 'work_allocation_history', ['batch_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_history_property_id'), 'work_allocation_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_history_ticket_id'), 'work_allocation_history', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_work_allocation_history_zone_id'), 'work_allocation_history', ['zone_id'], unique=False)
    op.add_column('maintenance_tickets', sa.Column('zone_id', sa.Uuid(), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('allocation_batch_id', sa.Uuid(), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('allocation_status', sa.String(length=32), server_default='unassigned', nullable=False))
    op.add_column('maintenance_tickets', sa.Column('allocation_method', sa.String(length=32), nullable=True))
    op.add_column('maintenance_tickets', sa.Column('allocation_reason', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_maintenance_tickets_allocation_batch_id'), 'maintenance_tickets', ['allocation_batch_id'], unique=False)
    op.create_index(op.f('ix_maintenance_tickets_zone_id'), 'maintenance_tickets', ['zone_id'], unique=False)
    op.create_foreign_key('fk_maintenance_tickets_zone_id', 'maintenance_tickets', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_maintenance_tickets_alloc_batch', 'maintenance_tickets', 'work_allocation_batches', ['allocation_batch_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('allocation_batch_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('allocation_status', sa.String(length=32), server_default='unassigned', nullable=False))
    op.add_column('tasks', sa.Column('allocation_method', sa.String(length=32), nullable=True))
    op.add_column('tasks', sa.Column('allocation_reason', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tasks_allocation_batch_id'), 'tasks', ['allocation_batch_id'], unique=False)
    op.create_foreign_key('fk_tasks_alloc_batch', 'tasks', 'work_allocation_batches', ['allocation_batch_id'], ['id'], ondelete='SET NULL')
    # Sequence for WB-YYYY-NNNNN batch numbers
    op.execute("CREATE SEQUENCE IF NOT EXISTS work_batch_seq START 1")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS work_batch_seq")
    op.drop_constraint('fk_tasks_alloc_batch', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_allocation_batch_id'), table_name='tasks')
    op.drop_column('tasks', 'allocation_reason')
    op.drop_column('tasks', 'allocation_method')
    op.drop_column('tasks', 'allocation_status')
    op.drop_column('tasks', 'allocation_batch_id')
    op.drop_constraint('fk_maintenance_tickets_zone_id', 'maintenance_tickets', type_='foreignkey')
    op.drop_constraint('fk_maintenance_tickets_alloc_batch', 'maintenance_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_tickets_zone_id'), table_name='maintenance_tickets')
    op.drop_index(op.f('ix_maintenance_tickets_allocation_batch_id'), table_name='maintenance_tickets')
    op.drop_column('maintenance_tickets', 'allocation_reason')
    op.drop_column('maintenance_tickets', 'allocation_method')
    op.drop_column('maintenance_tickets', 'allocation_status')
    op.drop_column('maintenance_tickets', 'allocation_batch_id')
    op.drop_column('maintenance_tickets', 'zone_id')
    op.drop_index(op.f('ix_work_allocation_history_zone_id'), table_name='work_allocation_history')
    op.drop_index(op.f('ix_work_allocation_history_ticket_id'), table_name='work_allocation_history')
    op.drop_index(op.f('ix_work_allocation_history_property_id'), table_name='work_allocation_history')
    op.drop_index(op.f('ix_work_allocation_history_batch_id'), table_name='work_allocation_history')
    op.drop_table('work_allocation_history')
    op.drop_index(op.f('ix_work_allocation_batches_zone_id'), table_name='work_allocation_batches')
    op.drop_index(op.f('ix_work_allocation_batches_property_id'), table_name='work_allocation_batches')
    op.drop_index(op.f('ix_work_allocation_batches_employee_id'), table_name='work_allocation_batches')
    op.drop_index(op.f('ix_work_allocation_batches_company_id'), table_name='work_allocation_batches')
    op.drop_index(op.f('ix_work_allocation_batches_batch_number'), table_name='work_allocation_batches')
    op.drop_table('work_allocation_batches')
    op.drop_index(op.f('ix_zone_allocation_state_zone_id'), table_name='zone_allocation_state')
    op.drop_index(op.f('ix_zone_allocation_state_property_id'), table_name='zone_allocation_state')
    op.drop_table('zone_allocation_state')
    # ### end Alembic commands ###
